[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = [
  "npx prisma generate --schema=backend/prisma/schema.prisma",
  "npm run build --workspace=shared",
  "npm run build --workspace=backend"
]

[start]
cmd = "npm run start --workspace=backend"
